# Oauth2
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
          kakao:
            client-id: YOUR_KAKAO_CLIENT_ID
            client-secret: YOUR_KAKAO_CLIENT_SECRET
            scope: profile, account_email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            client-name: Kakao
          naver:
            client-id: YOUR_NAVER_CLIENT_ID
            client-secret: YOUR_NAVER_CLIENT_SECRET
            scope: name, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.id

# h2
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/dofarming
#    username: sa
#    password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#        show-sql: true

# MongoDB
  data:
    mongodb:
      uri: mongodb://root:root@43.203.241.172:27017/mongodb?authSource=admin

# Mail
  mail:
    host: smtp.gmail.com
    username: wlzhf12@gmail.com
    password: hzfzbcoyeojujbnj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

## Server Prefix
#server:
#  servlet:
#    context-path: /api/v1
#  port: 8080

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# JWT
jwt:
  expiration_time: 86400000
  secret: 481dcf8765f96663663aa13c87a26791903df60226ee22a23a091de1a3005166f55fb511fa29157da5d02a639ff93ecb44c5ee9c68d97bcb042f412139d52a48

# Image Path
image:
  file:
    path: /Users/leeho/Pictures/
