name: Deploy to Amazon EC2

on:
  push:
    branches:
      - "main"
#      - "develop"

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: dofarming-be-bucket
  CODE_DEPLOY_APPLICATION_NAME: dofarming-codeDeploy-BE-ubuntu
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: dofarming-codeDeploy-BE-ubuntu-group

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x dofarming/gradlew

      - name: Build with gradle
        run: cd dofarming && ./gradlew clean build --no-daemon -x test

      - name: Create application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > dofarming/src/main/resources/application.properties

      - name: Create zip file
        run: zip -r dofarmingV2-${{ github.sha }}.zip dofarming/build/libs/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Upload to AWS S3
#        run: aws s3 cp dofarming.zip s3://${{ env.S3_BUCKET_NAME }}/$GITHUB_SHA.zip
#        run: aws s3 cp dofarmingV2-${{ github.sha }}.zip s3://${{ env.S3_BUCKET_NAME }}/dofarmingV2-${{ github.sha }}.zip
        run: |
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://${{env.S3_BUCKET_NAME}}/dofarmingV2-${{ github.sha }}.zip \
            --source .

      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=dofarmingV2-${{ github.sha }}.zip,bundleType=zip